### ISSUE TITLE
Clearification of the DILCISBoard SIARD versus eCH-0165 SIARD

### ISSUE THREAD

**Issue by solfeggietto** [DILCISBoard/SIARD#41]
The official eCH-0165 SIARD-Formatspecification as developed by the eCH Fachgruppe on Digital Preservation, originated from the Swiss National Archives.
https://kost-ceco.ch/cms/index.php?siard_de

Is this DILCISBOARD SIARD i am writing on now the current site to review the SIARD-standard, with issues, suggestions and interoperability concerns of the existing SIARD-tools? 

The latest SIARD 2.1.1 Format Specification lists the Autors of that spec and also includes some members of the DILCISBoard.

**Comment by andersbonielsen** [comment]
The DILCIS Board SIARD repository has been created to (among other purposes) clarify these matters with different versions of the specification. @DILCISBoard/siard-working-group @audunlund
The SIARD Working Group will in the coming weeks and months address this issue and list all previous and current specifications.
We intend this site, this repository, to be the place to address such issues with the specification.
More clarification will follow.
