### ISSUE TITLE
DILCISBoard SIARD by practical examples?

### ISSUE THREAD

**Issue by solfeggietto** [DILCISBoard/SIARD#44]
I am not sure uf posting an Issue here at the DILCISBoard SIARD is the correct place.

The use of SIARD as the preferred extraction format for old electronis system archiving is accelerating in Norway. Our regional and national municipal projects supports and recommend the use and knowledge building of all the currently available SIARD-tools ([DBPTK](https://www.database-preservation.com/), [DBVTK](http://visualization.database-preservation.com/), [SIARD Suite](https://www.bar.admin.ch/bar/en/home/archiving/tools/siard-suite.html), [SCFC](https://www.spectralcore.com/fullconvert) and [Documaster Decom](https://www.documaster.com/en/documaster_decom)).

It would be very useful to have a site to exchange experiences and file problems and solutions and suggestions of SIARD-tool usages.

Perhaps its onw GitHub project for SIARD user experiences? Or another type of site for FAQs?

As an example, i downloded  the latest SIARD Gui v2.1.105 yesterday. Failed to connect to our MSSQL 2014 database, that another tool connected to immediately. Successfully connected and extracted from MySQL 5.6.35 and i could see that the SIARD file was filled with MBs in size, but then SIARD Gui reported 'Archive "D:\arkiv-demo\testdb.siard" is invalid!' and aborted.

I am sure other users may have experienced this, and when some find a solution this would be posted and all users would benefit the experience sharing. Connection string examples of different database types and cases is a common challenge, as we cannot all be expert at all kinds of databases and usages...

Now detected BUGS will be filed at the individual Tools site or method for reporting this. But initially, it will be wise to read a FAQ site of user experiences for all SIARD-usages, as the most user problems can be solved by better knowledge and usually is not a bug at all.

**Comment by andersbonielsen** [comment]
The DILCISBoard/SIARD repository currently has its focus on the SIARD file format specifiation, not the tools supporting the file format specifiation. 
Naturally, issues regarding the format specification will arise in connection with the use of the tools.
There are already GitHub repos for the open source tools supporting the format specification, and issues reg. these tools should be raised at their repo.
More general issues regarding the use of the SIARD file format spec. and the tools supporting it can be addressed here until a seperate repo may be needed.
The SIARD Working Group will create labels and a Wiki to support this.
