### ISSUE TITLE
New optional/mandatory element: Database authorship

### ISSUE THREAD

**Issue by MartinR4838** [DILCISBoard/SIARD#49]
Since databases are protected by Directive 96/9/EC we should know who is the author of the database when acquiring it.
[https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A31996L0009](url)

**Comment by PhillipTommerholt** [comment]
Hi Martin
Thank you for your comment. I have briefly skimmed the directive and will read it more intensively at a later point.
But in the meanwhile: I guess the bottom line that there is a dataOwner and a databaseAuthor which might not be the same? A standard system for example which is in use in different organizations, and hence the different data in the databases have different dataOwners but the same databaseAuthor?

I can see a possible solution like this in metadata.xml:

Current first elements is this:
```
<dbname>
<dataOwner>
<dataOriginTimespan>
<>
```

Possible first elements could be this:
```
<dbname>
<dataOwner>
<databaseAuthor>
<dataOriginTimespan>
<>
```

We are in E-ARK3 currently beginning to work on a Content Information Type Specification for Relational Databases using SIARD describing how to store SIARD-files in an [CSIP-package](https://earkcsip.dilcis.eu/) - and here another solution could be to have extra metadata and context documentation in files outside the SIARD-file within an CSIP-package - as the SIARD standard also recommends: 
![image](https://user-images.githubusercontent.com/15984159/75423729-9375bd00-593f-11ea-9f5e-db34088b1291.png)

So I think there needs to be a discussion on where to put information like this.

Best regards
Phillip

**Comment by MartinR4838** [comment]
Hi Phillip,

at this moment it´s just food for thought but the Legislation is clear especially in the articles 3 and 4. In my my eyes is <dataOwner> element place for information about producer/institution which run and filled database with data during <dataOriginTime-span>. And element <databaseAuthor> can/should contain information who created the database. Structure of the database is apparently protected by copyright (article 3). I think that only in a minority of cases would these elements be the same. Determining database copyright may be a problem because some tables/functions can be added at the customer´s request but we should preserve this information and be aware of copyright.

**Comment by MartinR4838** [comment]
... eyes is element dataOwner
And element databaseAuthor can/should...

**Comment by MartinR4838** [comment]
..during element dataOriginTime-span...
clauses caused missing elements information. Sorry for that.

**Comment by MartinR4838** [comment]
And yes different data owners with same database author. It is common situation for small producers in CZ like schools, municipalities etc.

**Comment by PhillipTommerholt** [comment]
> ...t but we should preserve this information and be aware of copyright.

Definitely. In the Danish National Archives where I work - we are also very aware of this, and we do not hand out system information.

**Comment by audunlund** [comment]
This is a matter of documentation and should go into the CITS.
