### ISSUE TITLE
New optional element: License conditions

### ISSUE THREAD

**Issue by MartinR4838** [DILCISBoard/SIARD#50]
If archivist decides to preserve a database (community driven Timemachine etc.) that has been published under the license terms like Creative Commons, then such information should have been included in the metadata.
[https://creativecommons.org/use-remix/cc-licenses/](url)

**Comment by MartinR4838** [comment]
For example the capital city Prague is developing smart city data platform Golemio www.golemio.cz under MIT license which is open source and any city administration can use it and implement to their data infrastructure.

**Comment by audunlund** [comment]
This is a matter of documentation and should go into the CITS.

**Comment by kuldaraas** [comment]
Yes, the CITS might offer an option for adding a DCAT-AP dataset+distribution description next to the SIARD file and metadata.
