### ISSUE TITLE
Conversion from Access to SIARD fails with java.lang.illegalArgumentException

### ISSUE THREAD

**Issue by BloodyStupidUser** [DILCISBoard/SIARD#59]
I have 2 Access Databases that I need to convert. The first worked well. The same procedure with the second DB fails. SIARD terminates, giving the error:

> Meta Data
>   Table: UWAD_ZH."A2_Pos&SK"
>   Table: UWAD_ZH."A4_Fund"
>   java.lang.IllegalArgumentException: Column A4_Fund].[FKnr of A4_Fund; not found!
> 

The problem is that the message makes no sense: There is a Column "FKnr" in the table "A4_Fund". So it doesn't point me to any solution. 
It is really not a complex or difficult database. So I am quite stuck.
Any ideas?

**Comment by MartinR4838** [comment]
Hi, you should rather ask on tool´s developer Git than here. I would guess FKnr to be Foreign Key and tool can´t find related table.

**Comment by BloodyStupidUser** [comment]
Hi Martin
I have no idea what you mean by "the tool's developer git". Where is that? I have searched for SIARD and this is where I arrived.
Anyway - You are right in that FKnr is a foreign key, but the related table is in the same database and I don't see why the SIARD suite should not find it.

**Comment by MartinR4838** [comment]
Hi BloodyStupidUser,

I mean Git where you´ve downloaded tool. SIARD Suite https://github.com/sfa-siard/SiardGui/issues. You can DBPTK https://github.com/keeps/dbptk-developer/releases/tag/v2.10.3 too, may be you´ll be more successful.

Best

**Comment by BloodyStupidUser** [comment]
OK, thanks. I have downloaded it elsewhere, and I'm completely new to GitHub...
Thanks a lot!

**Comment by audunlund** [comment]
It is correct what [MartinR4838](https://github.com/MartinR4838) stated. This has to be reported to the tool producer and has noting to do with the SIARD Format.
