### ISSUE TITLE
Db-preservation-toolkit, SIARD not updated on COPTR

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/SIARD#6]
Community Owned digital Preservation Tool Registry (COPTR) is maintained by OPF.
For DBPTK, it is not mentioned that the tool can export/import SIARD:

http://coptr.digipres.org/Db-preservation-toolkit

**Comment by PhillipTommerholt** [comment]
Just to let you know @hsilva-keep
(I am not sure how widely this tool registry is used by the digital preservation community.)

**Comment by hsilva-keep** [comment]
@PhillipTommerholt thank you for the information...I'll pass it on internally in order to get that registry entry updated...

**Comment by luis100** [comment]
Updated.

@PhillipTommerholt if you'd like for me to add links to documents detailing your user experience please send me those.

**Comment by hsilva-keep** [comment]
@PhillipTommerholt Luis has updated the registry entry. I'll set you as the assignee of this issue, and if your comfortable with the changes, please close the issue. Otherwise, provide extra information.

**Comment by PhillipTommerholt** [comment]
Thanks!
