### ISSUE TITLE
Process failed when importing a Siard file into a Sql Server database of the schema name contains "_" 

### ISSUE THREAD

**Issue by bt-cgi** [DILCISBoard/SIARD#63]
Hello,

When importing a Siard file into a SQL Server database into a schema whose the name contains the character "_", the process checks if the schema already exists with the following query:

select sys.schemas.name 'TABLE_SCHEM', CASE WHEN sys.schemas.name  IN  ('dbo', 'guest','INFORMATION_SCHEMA','sys','db_owner', 'db_accessadmin', 'db_securityadmin',
'db_ddladmin'  ,'db_backupoperator','db_datareader','db_datawriter','db_denydatareader','db_denydatawriter')  THEN null ELSE  DB_NAME()  END 'TABLE_CATALOG'
from sys.schemas where sys.schemas.name like N'DBA\_JBP'   order by 2, 1

The query doesn't work because the escape character "\" behind the "_" is ignored in SQL Server (it may be specific to Oracle databases).

If the schema already exists, the query don't find it and the process try to create it, that makes it fail.

**Comment by mbangerter** [comment]
Hello, 
Many thanks for your report. Just one question: Am I right in assuming that the problem occurs when using SIARD Suite?

**Comment by bt-cgi** [comment]
Hello,

The problem occurs when using SIARD Suite and when using SIARD suites command line tool.

Regards

De : mbangerter ***@***.***>
Envoyé : jeudi 11 juillet 2024 11:33
À : DILCISBoard/SIARD ***@***.***>
Cc : Thenard, Benoît ***@***.***>; Author ***@***.***>
Objet : Re: [DILCISBoard/SIARD] Process failed when importing a Siard file into a Sql Server database of the schema name contains "_" (Issue #63)

EXTERNAL SENDER: Do not click any links or open any attachments unless you trust the sender and know the content is safe.
EXPÉDITEUR EXTERNE: Ne cliquez sur aucun lien et n’ouvrez aucune pièce jointe à moins qu’ils ne proviennent d’un expéditeur fiable, ou que vous ayez l'assurance que le contenu provient d'une source sûre.



Hello,
Many thanks for your report. Just one question: Am I right in assuming that the problem occurs when using SIARD Suite?

**Comment by mbangerter** [comment]
As commented issue #64, may I ask you to report the error directly in the corresponding repo (https://github.com/sfa-siard/siard-suite) ? Thanks in advance and best

**Comment by bt-cgi** [comment]
Ok, thank you for your help.
